### ISSUE TITLE
Unnecessary tests for enchant

### ISSUE THREAD

**Issue by Aethys255** [SimCMinMax/AutoSimC#1]
We don't need the elif and some line of the array of enchant.
I prefer to let it as it is atm until I found a better way to do an array of enchant available without specifying it manually.

**Comment by Kutikuti** [comment]
Old but maybe some cleanup :
Do we still have to keep the enchant permutation part ? (l231+) I could redo some of it if you are interested in keeping it

**Comment by Kutikuti** [comment]
Scrapped unused code
