### ISSUE TITLE
Combining the results

### ISSUE THREAD

**Issue by Maheine** [SimCMinMax/AutoSimC#16]
Hi,

in the old versions I used for default_top_n_stage3 values from 5 to 20 to get the x best combinations in one result. In the newer versions the result dir contains x result files, eg. for value 5 

best0-2017-12-06_14-40-59.html
best1-2017-12-06_14-40-59.html
best2-2017-12-06_14-40-59.html
best3-2017-12-06_14-40-59.html
best4-2017-12-06_14-40-59.html

Is there a way to combine them by a parameter, so I get all results in one file?

Regards,
Maheine

**Comment by scamille** [comment]
Hi,

As long as you have <50 profiles in the last stage, you should still get only 1 html file.

default_top_n_stage3 (or now default_top_n) is only used if default_use_alternate_grabbing_method is False, which I would not really recommend.

If that is somehow not the case for you with the latest version, please attach your input.txt and command line arguments so we can try to reproduce the problem.

**Comment by Maheine** [comment]
cli: python main.py

[autosim.zip](https://github.com/SimCMinMax/AutoSimC/files/1536815/autosim.zip)

**Comment by Maheine** [comment]
The version from 05.12. did not combine, the version from today did. So everything is fine.

Besides:
It worked with Python 3.6 on Windows.


Centos with Pyhton 2.6.6 & Python 2.7.5
```
[root AutoSimC]# python main.py
  File "main.py", line 92
    slot, item_id, *tail = legendary_split
                   ^
SyntaxError: invalid syntax

```
Centos with python 3.4.5
```
python3 main.py
  File "main.py", line 171
    choices=['permutate_only', 'all', *("stage{}".format(i) for i in range(1, 6))],
                                                             ^
SyntaxError: can use starred expression only as assignment target


```

**Comment by scamille** [comment]
Thanks for that last part. I intend to have 3.4 supported, but not any Python2.x.

That usage of * to flatten the list crept back in just recently. I'll fix it. Most developers, including myself are on Python3.6, so maybe we need some CI integration to automatically test such things ;)
