### ISSUE TITLE
I cant get it to work for me

### ISSUE THREAD

**Issue by Richu58** [SimCMinMax/AutoSimC#19]
I followed all the instructions umren put on youtube and i use launch.bat it comes up with do you want to generate out .simc again? if i press y and enter it exits launch.bat, if i hit n and enter it goes on to ask if i want static or dynamic, then no matter what i enter after i hit enter it exits.

**Comment by scamille** [comment]
Please run launch.bat from a command line shell (cmd.exe or PowerShell). An easy way to do so is if you are in the AutoSimC folder, Shift-Rightclick and select "Open PowerShell window here". Then run ./launch.bat

Then run again and check what error messages you get, post them or a screenshot here please.

At least AutoSimC seems to be running if you get the questions you mention. But something with launching SimulationCraft seems to be not ok.

**Comment by scamille** [comment]
Closing this for now.

If you still need some help in getting AutoSimC to run in general, please contact us on Discord (see README).
