### ISSUE TITLE
Error: local variable 'class_spec' referenced before assignment

### ISSUE THREAD

**Issue by D-Kay** [SimCMinMax/AutoSimC#28]
I was getting the following error after setting up the latest version AutoSimC and launching it (through launch.bat)

Error: local variable 'class_spec' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 1633, in <module>
    main()
  File "main.py", line 1589, in main
    player_profile = build_profile(args)
  File "main.py", line 864, in build_profile
    player_profile.class_spec = specdata.getClassSpec(c_class, player_profile.simc_options["spec"])
  File "C:\AutoSimC-master\specdata.py", line 594, in getClassSpec
    return class_spec
UnboundLocalError: local variable 'class_spec' referenced before assignment
Press any key to continue . . .

I went to line 594 in specdata.py and it looked like `return class_spec` was missing 4 spaces. Adding them made the program work correctly

I'm using Windows 10, the latest version of SimC and Python (3.6.5)

**Comment by scamille** [comment]
The problem is more that we probably don't have all class/spec combinations covered.

Can you try again with my changes? And if you get an error message about unsupported class/spec, post it here please.
