### ISSUE TITLE
Unable to run launch.bat gives SyntaxError: invalid syntax on line 809 in main.py

### ISSUE THREAD

**Issue by Diluted22** [SimCMinMax/AutoSimC#39]
When I try to run the launch.bat i get the following error

![image](https://user-images.githubusercontent.com/19807537/46710635-9f06fd80-cbfd-11e8-9dcd-8df982442363.png)

**Comment by scamille** [comment]
Apparently you don't get the full error message through launch.bat

If you run main.py directly, you'll get the following error:
Error: AutoSimC could not decode your input file 'input.txt' with encoding 'utf-8'.
        Please make sure that your text editor encodes the file as 'utf-8',
        or as a quick fix remove any special characters from your character name.

See also https://github.com/SimCMinMax/AutoSimC#frequently-asked-questions question 1
