### ISSUE TITLE
simc auto download doenst work anymore

### ISSUE THREAD

**Issue by Nexxxy** [SimCMinMax/AutoSimC#45]
Sometimes files are called and downloaded like :

simc-815-02-win64-nonetwork-d705c6c3fd

witch results in simc-815-02-win64-nonetwork folder. This one cant be detected by the script.

And sometimes the autoupdate doesnt work. He doesnt recognize the version update too.

Greetings

**Comment by scamille** [comment]
https://github.com/SimCMinMax/AutoSimC/blob/master/main.py#L339

the regex there probably needs to be updated to exclude nonetworking.

I'll see if I can find some time to get that fixed.
