### ISSUE TITLE
IndexError: List index out of range

### ISSUE THREAD

**Issue by Skyrisu** [SimCMinMax/AutoSimC#5]
I imported the simpermut export used the default command and got this error:
EDIT: I dont know if this is an error, but it seems odd. In line 92 it says "elif ex[0]=='wrist': " ist the Ex intended?
`Traceback (most recent call last):
 File "main.py", line 188, in <module>
    handlePermutation(elements)
  File "main.py", line 115, in handlePermutation
    addToTab(pieces)
  File "main.py", line 81, in addToTab
    stringToAdd="L,id="+x[1]+(",bonus_id="+x[2] if x[2]!="" else "")+(",enchant_id="+x[3] if x[3]!="" else "")+(",gem_id="+x[4] if x[4]!="" else "")
IndexError: list index out of range`

**Comment by Kutikuti** [comment]
not intended for the ex imo. Fixed that.
For your problem, could you provide the settings.ini that you are using ?
Is the output file generated ?

**Comment by Skyrisu** [comment]
Everything is working now, thank you!
